# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [2]:
import numpy as np 

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.array(([0,1,2],[3,4,5],[6,7,8]))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.array(([1.,0.,0.],[0.,1.,0.],[0.,0.,1.]))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand(1)

array([0.14639114])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.randn(5,5)

array([[ 2.89296169, -0.5843536 ,  1.93646979, -0.13289588,  0.38901066],
       [ 0.4960237 , -0.26703584,  0.50694522,  1.24786808,  0.17851081],
       [ 0.19110315, -0.05147426,  0.80362134, -0.03366029, -1.74689816],
       [-0.33778261,  0.61630774,  0.5350045 ,  1.55166492, -0.87404064],
       [-0.92935015, -1.85931592,  1.02627013,  0.4575381 ,  0.57408265]])

#### Create the following matrix:

In [21]:
array = np.zeros((10,10))
for i in range (10):
    for j in range(10):
        array[i][j]=(0.1)*i+(0.01)*(j+1)
        
print(array)        
    

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [40]:
array = np.zeros((5,5))

for i in range(5):
    for j in range(5):
        array[i][j] =5*i+j+1
    
print(array)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [29]:
array = np.zeros((3,4))

for i in range(3):
    for j in range(4):
        array[i][j] =11+4*i+j+1
    
print(array)

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]


In [31]:
array = np.zeros((1,1))
for i in range (1):
    for j in range (1):
        array[i][j]=20
        
print (array)        
    

[[20.]]


In [33]:
 array = np.array(([ 2],[ 7],[12]))

In [36]:
array = np.arange (21,26)
array


array([21, 22, 23, 24, 25, 26])

In [49]:
array=np.arange(16,26)
array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [41]:
s = 0 
for i in range (5):
    for j in range(5):
        s+=array[i][j]
print(s)        

325.0


#### Get the standard deviation of the values in mat

In [43]:
sd = np.std(array)
sd


7.211102550927978

#### Get the sum of all the columns in mat

In [44]:
s = 0 
for i in range (5):
    
    s+=array[i]
print(s)

[55. 60. 65. 70. 75.]


# Great Job!